name:                advent-of-code2025
version:             0.1.0.0
description:         "advent-of-code2025"

dependencies:
- base >= 4.7 && < 5
- text
- containers
- unordered-containers
- hashable
- vector
- split
- safe
- either
- megaparsec
- optparse-applicative
- witherable
- neat-interpolation
- recursion-schemes
- data-fix
- pretty
- comonad
- distributive
- adjunctions
- machines
- algebraic-graphs
- ansi-terminal
- envparse
- req
- bytestring
- mtl
- aeson
- aeson-pretty
- array
- parser-combinators
- tardis

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages
  - -O2

library:
  source-dirs: src

executables:
  aoc2025:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code2025

tests:
  aoc2025-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0 # No optimisation for faster test runs
    dependencies:
    - advent-of-code2025
    - hspec
    - hspec-discover
    - QuickCheck
    build-tools:
    - hspec-discover

benchmarks:
  aoc2025-benchmarks:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-s
    dependencies:
      - advent-of-code2025
      - base
      - criterion

verbatim:
  cabal-version: 3.0
